FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
#ENV API_KEY
EXPOSE 8080

# The app.py file expects an environment variable called 'API_KEY' to start.
# The app.py file is hardcoded to listen on port 8080 internally.
CMD ["python", "app.py"]
